using System.Runtime.InteropServices;

namespace Ray2Mod.Game.Structs.AI.BehaviourEnums {
    public enum BehaviourEnums_YLT_RaymanModel_Normal {
        YLT_Init,
        YLT_Attente,
        YLT_SautReception,
        YLT_SautMontee,
        YLT_Helico,
        BNT_Nage,
        YLT_BlocMode,
        BNT_Grappin,
        YLT_GiBlocMode,
        YLT_Reinit,
        YLT_Desactive,
        YLT_EntreDeux,
        YLT_EntreDeuxAvance,
        YLT_EntreDeuxRecul,
        CHG_RaymanPaf,
        CHG_RayPafAir,
        CHG_RayPafEau,
        CHG_RayPafEcrase,
        YLT_PafSol,
        YLT_TonneauFuseeComport,
        YLT_Vide,
        BNT_RayPafAttendLaMort,
        YLT_PafGi,
        YLT_ChuteInfinie,
        YLT_SautImpulsion,
        BNT_DansLeSiegeRusse,
        YLT_SautSommet,
        YLT_Varappe,
        BNT_TonneauAttente,
        BNT_TonneauMarcheAvant,
        YLT_GiAttente,
        YLT_GiMarche,
        BNT_AccrocheAuBord,
        BNT_AccrocheRemonte,
        BNT_NagePlonge,
        BNT_NageSaute,
        BNT_WalkRunComport,
        BNT_AccrocheTentatives,
        BNT_NewPatin,
        BNT_PafElectrique,
        BNT_Atterrissage,
        BNT_Basket,
        BNT_TransePolochusComport,
        BNT_FadeDeLaMort,
        BNT_FadeDeLaMortBis,
        BNT_InitSuiteEtFin,
    }

    public enum BehaviourEnums_YLT_RaymanModel_Reflex {

        BNT_ReflexeMort,
        YLT_AucunReflexe,
        YLT_SautDetecteSol,
        YLT_ReflexeAttente,
        YLT_SautCourant,
        JAC_GiReflexe,
        BNT_ReflexeNage,
        BNT_ReflexeGrappin,
        CHG_VarREflexe,
        FRD_Entr2Reflexe,
        BNT_TonneauFuseeReflexe,
        BNT_ReflexeDansLeSiegeRusse,
        BNT_ReflexeTonneauPorte,
        YLT_ReinitReflexe,
        BNT_ReflexePatin,
        BNT_SautImpulsionReflexe
    }
}